[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --prefix synqra-mvp"]

[phases.build]
cmds = ["npm --prefix synqra-mvp run build"]

[start]
cmd = "npm --prefix synqra-mvp run start"
