[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = [
  "export PATH=$PATH:/root/.local/share/pnpm",
  "pnpm install --filter ./apps/synqra-mvp..."
]

[phases.build]
cmds = [
  "pnpm --filter ./apps/synqra-mvp build"
]

[start]
cmd = "cd apps/synqra-mvp && pnpm start"
