[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd noid-dashboard && npm install"]

[phases.build]
cmds = ["cd noid-dashboard && npm run build"]

[start]
cmd = "cd noid-dashboard && npm run start"
